version: '3'
services:
  web:
    build: .
    environment:
     - PORT=8080
    ports:
     - "8080:8080"
#    links:
#     - redis-master
#     - redis-slave
##     - redis
#  redis-master:
#    image: redis:alpine
#    volumes:
#        - "./redis_data:/data"
#  redis-slave:
#    image: redis:alpine
#    links:
#        - redis-master
#        - redis-master:master
#    command: "redis-server --slaveof master 6379"
##  redis:
##    image: "redis:alpine"
##    expose:
##     - "6379"

